package com.integral.ds.tradeepafieldupdater.dao;

import com.integral.ds.tradeepafieldupdater.model.InternalTradeEpa022016;
import com.integral.ds.tradeepafieldupdater.model.InternalTradeEpa022016Example;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface InternalTradeEpa022016Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internal_trade_epa_02_2016
     *
     * @mbggenerated Mon Feb 08 13:18:32 COT 2016
     */
    int countByExample(InternalTradeEpa022016Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internal_trade_epa_02_2016
     *
     * @mbggenerated Mon Feb 08 13:18:32 COT 2016
     */
    int deleteByExample(InternalTradeEpa022016Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internal_trade_epa_02_2016
     *
     * @mbggenerated Mon Feb 08 13:18:32 COT 2016
     */
    int insert(InternalTradeEpa022016 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internal_trade_epa_02_2016
     *
     * @mbggenerated Mon Feb 08 13:18:32 COT 2016
     */
    int insertSelective(InternalTradeEpa022016 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internal_trade_epa_02_2016
     *
     * @mbggenerated Mon Feb 08 13:18:32 COT 2016
     */
    List<InternalTradeEpa022016> selectByExample(InternalTradeEpa022016Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internal_trade_epa_02_2016
     *
     * @mbggenerated Mon Feb 08 13:18:32 COT 2016
     */
    int updateByExampleSelective(@Param("record") InternalTradeEpa022016 record, @Param("example") InternalTradeEpa022016Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internal_trade_epa_02_2016
     *
     * @mbggenerated Mon Feb 08 13:18:32 COT 2016
     */
    int updateByExample(@Param("record") InternalTradeEpa022016 record, @Param("example") InternalTradeEpa022016Example example);
    
    List<InternalTradeEpa022016> selectByStatus(String status);

}